# -*- coding: utf-8 -*-
"""Copy of Linearregression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_O6VdMMubmmp3Q6TReIHzZr3OjfKxJRz

Import Necessary Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error

"""Load the Data"""

data = pd.read_csv('/Real estate.csv')

"""Preprocess the Data"""

X = data.drop('X2 house age', axis=1)
y = data['Y house price of unit area']

print("Summary Statistics:")
print(data.describe())

print("\nMissing Values:")
print(data.isnull().sum())

data.hist(bins=20, figsize=(15,10))
plt.show()

plt.figure(figsize=(15,10))
sns.boxplot(data=data)
plt.show()

plt.figure(figsize=(15,10))
sns.pairplot(data)
plt.show()

plt.figure(figsize=(12, 8))
sns.heatmap(data.corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.show()

"""Split the Data into Training and Testing Sets"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""Train the Linear Regression Model"""

model = LinearRegression()
model.fit(X_train, y_train)

"""Make Predictions"""

y_pred = model.predict(X_test)

"""Evaluate the Model"""

mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)

print("Mean Squared Error (MSE):", mse)
print("Mean Absolute Error (MAE):", mae)
print("Root Mean Squared Error (RMSE):", rmse)